services:
  - type: web
    name: watch-management-api
    env: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npx tsc
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
